// Auto-generated by tools/generate-local-cards.ps1.
// Edit english/chinese values after generation if the file names are not the desired words.

window.LOCAL_CARD_GROUPS = [
    {
        "grade":  "中班上学期",
        "group":  "color",
        "cards":  [
                      {
                          "english":  "blue",
                          "chinese":  "",
                          "image":  "cards/中班上学期/color/blue.jpg"
                      },
                      {
                          "english":  "yellow",
                          "chinese":  "",
                          "image":  "cards/中班上学期/color/yellow.jpg"
                      }
                  ]
    },
    {
        "grade":  "中班下学期",
        "group":  "color",
        "cards":  [
                      {
                          "english":  "blue",
                          "chinese":  "",
                          "image":  "cards/中班下学期/color/blue.jpg"
                      },
                      {
                          "english":  "yellow",
                          "chinese":  "",
                          "image":  "cards/中班下学期/color/yellow.jpg"
                      }
                  ]
    }
];
