$cardsRoot = Join-Path $PSScriptRoot "..\cards"
$outputPath = Join-Path $cardsRoot "local-cards.js"
$imageExtensions = @(".jpg", ".jpeg", ".png", ".webp", ".gif")
$existingCardsByImage = @{}

if (Test-Path -LiteralPath $outputPath) {
  $existingContent = Get-Content -Raw -Encoding utf8 -LiteralPath $outputPath
  $entryPattern = '(?s)\{\s*"?english"?\s*:\s*"([^"]*)"\s*,\s*"?chinese"?\s*:\s*"([^"]*)"\s*,\s*"?image"?\s*:\s*"([^"]*)"\s*,?\s*\}'
  [regex]::Matches($existingContent, $entryPattern) | ForEach-Object {
    $existingCardsByImage[$_.Groups[3].Value] = @{
      english = $_.Groups[1].Value
      chinese = $_.Groups[2].Value
    }
  }
}

$groups = @(Get-ChildItem -LiteralPath $cardsRoot -Directory | Sort-Object Name | ForEach-Object {
  $groupDirectory = $_
  $cards = @(Get-ChildItem -LiteralPath $groupDirectory.FullName -File |
    Where-Object { $imageExtensions -contains $_.Extension.ToLowerInvariant() } |
    Sort-Object Name |
    ForEach-Object {
      $english = [System.IO.Path]::GetFileNameWithoutExtension($_.Name) -replace "[-_]+", " "
      $relativePath = "cards/$($groupDirectory.Name)/$($_.Name)"
      $chinese = ""

      if ($existingCardsByImage.ContainsKey($relativePath)) {
        $english = $existingCardsByImage[$relativePath].english
        $chinese = $existingCardsByImage[$relativePath].chinese
      }

      [pscustomobject]@{
        english = $english
        chinese = $chinese
        image = $relativePath
      }
    })

  if ($cards.Count -gt 0) {
    [pscustomobject]@{
      group = $groupDirectory.Name
      cards = @($cards)
    }
  }
})

if ($groups.Count -eq 0) {
  $json = "[]"
} else {
  $json = ConvertTo-Json -InputObject @($groups) -Depth 6
}
$content = @"
// Auto-generated by tools/generate-local-cards.ps1.
// Edit english/chinese values after generation if the file names are not the desired words.

window.LOCAL_CARD_GROUPS = $json;
"@

Set-Content -LiteralPath $outputPath -Value $content -Encoding utf8
Write-Host "Generated $outputPath"
